# Generated by Django 6.0.4 on 2026-04-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
