# Generated by Django 6.0.4 on 2026-04-27 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_rooms_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
