# Generated by Django 6.0.4 on 2026-04-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reason',
            field=models.CharField(default='Occupied', verbose_name=[('Maintenance', 'MTC'), ('Occupied', 'OCC'), ('Out of Order', 'OOO')]),
        ),
    ]
