# Generated by Django 6.0.4 on 2026-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_rooms_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reason',
            field=models.CharField(default='Available', verbose_name=[('Maintenance', 'MTC'), ('Occupied', 'OCC'), ('Available', 'AVL'), ('Out of Order', 'OOO')]),
        ),
    ]
