# Generated by Django 6.0.4 on 2026-04-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_rooms_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_number',
            new_name='number',
        ),
    ]
