# Generated by Django 6.0.4 on 2026-04-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_rename_room_number_rooms_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='title',
        ),
    ]
