# Generated by Django 6.0.4 on 2026-04-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_remove_roomtype_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='room_type',
            new_name='title',
        ),
    ]
