# Generated by Django 6.0.4 on 2026-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_rooms_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reason',
            field=models.CharField(choices=[('MTC', 'Maintenance'), ('OCC', 'Occupied'), ('AVL', 'Available'), ('OOO', 'Out of Order')], default='AVL', max_length=3, verbose_name='Reasons - Maintenance = MTC, Occupied = OCC, Available = AVL, Out of Order = OOO'),
        ),
    ]
