# Generated by Django 6.0.4 on 2026-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_rooms_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='reason',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Occupied', 'Occupied'), ('Available', 'Available'), ('Out of Order', 'Out of Order')], default='Available', max_length=20, verbose_name='Reasons - Maintenance, Occupied, Available, Out of Order'),
        ),
    ]
