# Generated by Django 6.0.4 on 2026-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email Address'),
        ),
    ]
